### ISSUE TITLE
github permissions

### ISSUE THREAD

**Issue by slowkow** [astralapp/astral#1]
When I clicked "sign up", I got this:

```
Astral by @syropian would like permission to access your account

Repositories
Public only
This application will be able to read and write all public repo data.

This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
```

The [privacy policy](http://astralapp.com/privacy/) suggests that these permissions are not needed. Are they needed in order to un-star a repo?

I suspect that astral is asking for too many permissions. I was under the impression that astral would use the github API to retrieve stars like this:

https://api.github.com/users/syropian/starred

Does astral need permission to write to user repos? Does it need permission to create issues, pull requests, or wikis? I'm not interested to sign up for a service with those permissions.

**Comment by syropian** [comment]
Astral needs write permission to unstar repositories. Unfortunately I don’t have fine grain control over these permissions. One of my first priorities once I finish open sourcing is to rewrite the auth engine to be more opt-in, so for instance by default you can’t unstar repos unless you give Astral _additional_ access.
