### ISSUE TITLE
"edit tags" can't get any input on chrome and firefox

### ISSUE THREAD

**Issue by pantchox** [astralapp/astral#100]
when i want to "edit tags" of my " Untagged Stars" it let me write input for 2 seconds then delete the whole input, thus i can't add tags.
this happens when logging in and editing 1 star then when going to other to edit it deletes it and so on.

**Comment by muescha** [comment]
for me the same

workaround: click many times into and then try to have naybe the focus sometimes in the edit field with `tab` key
