### ISSUE TITLE
NPM ➡️ Yarn

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#101]
Will be experimenting with switching from NPM to [Yarn](https://yarnpkg.com) locally, and if all goes well, will also transition the live servers, which should speed up deploys quite a bit.

**Comment by alexbowers** [comment]
Laravel itself is making the switch, so this should be perfectly fine to change to. :)

**Comment by syropian** [comment]
Added in #104 , and added to production server. :shipit:
