### ISSUE TITLE
Astral is very slow loading stars, causing it not to work properly and causing browser to choke 

### ISSUE THREAD

**Issue by pantchox** [astralapp/astral#107]
Hello,
First i love astral i think its a very cool and it helps me organize my github stars as i wanted before knowing somthing like this exist, so i am happy there is Astral.

I love to star repos on github.. like a lot! (~1.6K).
Problem occurs when i login to Astral, it takes like few min to finish loading all my stars, by that time i can browse the stars that were already loaded, which is nice, but i can't perform actions such as editing (for adding/removing tags) , somehow there is something it causing not to work and i suspect its because its still loading stars in the background.

_Sidenote: While waiting for all the stars to load, until i come back my session expired and i need to relogin... The default session should be longer, its not a bank account._

Anyway i decided to take a look at chrome network tab to see what is going on  why it takes so much time.

### Analysis:
1. There are multiple requests to receive the stars, since Astral does not saves (only caches for 2 hours)  the stars of each user from the server side, so the client have to re-request the stars upon login longer then around 2 hours (this is what i was told in the gitter channel).
In my case there are 52 requests because each requests returns 30 github stars being pulled from github (via server side) and i have 1560 stars.

2. in the request to receive the stars, for EACH request (in my case 52) it also receive the tags you have created (in my case i have 590 tags), where each tag contains a reference to the star id 

### Conclusions

1. This sounds good but the problem is that if in the first request you are receiving 30 stars on the next your receive 60 and the next 90 and so on, you receive on each request what you ALREADY have, which is more data and more memory consumption and more processing i assume.
How it should work is that i should receive 30 (new) stars on each request and not including the previously received ones again.
2. each star comes with TONS of unnecessary data, like when was the branch created, who is the owner what are the permissions etc.. that is LOADS of data that is useless for using astral - which again more data processing and memory consumption and super slow Astral :(
3. on each request i have mentioned already (sorry) the tags object is attached, so for each request in my case i receive the tags again and again and again. this is not needed to send in each request the tags, they should even be on a separate API request before loading the stars (i assume this because Astral does not have currently in the UX a disabled loader until ALL stars are loaded so having the tags before sounds more reasonable)

This what makes me think Astral is slow, these issues can be solved.
I am sure there are a lot of users who gave up because of this, i wont.

**Comment by syropian** [comment]
Thanks for the writeup, I'll address a few things. 

1. This is something that I want to optimize over time, but I (literally) don't have the time. Complex server-side cases will eventually defer to @alexbowers , but he's just as busy as I am. There have just been too many other issues since the v2 launch to worry about.
2. I'm not sure the size of the responses is terribly important. I can't imagine slightly bigger objects in response data being a factor of slowing down the app. 
3. I'm not sure what you mean by load the tags beforehand, how can you show the tags before the stars are loaded in? Attaching the tags to the stars getting loaded in is to improve perceieved load time so the users aren't seeing a bunch of stars come in, and then have to wait for them to finish loading before seeing their tags applied.

I want to remind you that your case is rare and you are probably in the top 1% of Astral users in terms of how many starred repos you have. I realize it should be a one size fits all solution, but that's not always possible to get right on the first go.

**Comment by alexbowers** [comment]
Thank you for your thorough issue.

I'll try to address some of these points below, and create separate issues to track some of these.

Slow initial Page Load: #108

**Comment by alexbowers** [comment]
Just seen you response. I'll try to respond on a few things too.

**Comment by alexbowers** [comment]
@pantchox To help us test this in a more timely manner, would you possibly be able to create a test user on GitHub for us, which has many stars on it too?

Currently i'm too busy to be able to put much time in, but if I have an easy way to test it locally, that would be a big hurdle completed.

If you can send me and @syropian an email with a username and password of a new account with lots of stars that has the same issue as you are experiencing, we can focus on it sooner.

Thanks

**Comment by pantchox** [comment]
thanks guys for addressing this, i will help of course.
i will create a github user and will do a script to auto star the same stars that i have and i will send you my JSON tag object.
give 1-3 days. 

P.S 
i know its a side project and you do all the hosting and stuff and i think its amazing.
also for open source projects there are some places that give free hosting so that could help and maybe even have better server so better performance
for example - https://www.netlify.com/pricing/ (take a look at bottom right).

**Comment by alexbowers** [comment]
Rather than sending us the JSON, sending us access to the account with these stars will be more useful. Since many API calls are made, its much easier for us to test it against live accounts.

Once the account is ready (with stars on it), please email the username and password to bowersbros+astral107@gmail.com and we can then authenticate the user and test it.

Obviously, do not use a real password, but something meaningless (whether random characters, or a typical qwerty style password).

Thanks.

Alex.

**Comment by pantchox** [comment]
Hi, i have emailed you the credentials, the new user has exact ~1.6k stars like me.
In order to make it easy i created a VERY ROUGH draft script to copy stars from user to another that next time you will just need the username and the script will copy the stars for you for your new temp test user.
You can paste it in your chrome developer tools console window as long jQuery is presented (you can go to jquery.com and then inspect the page and use the console);

```javascript
function parse_link_header(header) {
    if (header.length === 0) {
        throw new Error("input must not be of zero length");
    }

    // Split parts by comma
    var parts = header.split(',');
    var links = {};
    // Parse each part into a named link
    for(var i=0; i<parts.length; i++) {
        var section = parts[i].split(';');
        if (section.length !== 2) {
            throw new Error("section could not be split on ';'");
        }
        var url = section[0].replace(/<(.*)>/, '$1').trim();
        var name = section[1].replace(/rel="(.*)"/, '$1').trim();
        links[name] = url;
    }
    return links;
};

function ajaxFetchStarsPage(url, starsArr, headers) {
    console.log('Fetching page - ' + url);
    headers = headers || {};
    $.ajax({
        type: "GET",
        url: url,
        dataType: 'json',
        async: false,
        headers: headers,
        success: function (data, textStatus, request) {
            var links = parse_link_header(request.getResponseHeader('Link'));
            $.each(data, function(idx, star){
                //console.log(star.full_name);
                starsArr.push(star.full_name);
            });

            if (links.next) {
                setTimeout(function() {ajaxFetchStarsPage(links.next, starsArr, headers);}, 1000); // 1 seconds delay
            } else {
                console.log('Done!');
            }
        }
    });
};

function fetchStars(username, password, githubUserName) {
    // get the first page
    var links = {
        next: 'https://api.github.com/users/' + githubUserName + '/starred?page=1'
    }

    var stars = [];
    var headers = {
        "Authorization": "Basic " + btoa(username + ":" + password)
    }

    ajaxFetchStarsPage(links.next, stars, headers); // recursive ...
    return stars;
};

var starRepo = function(url, headers, callback) {
            $.ajax({
                type: "PUT",
                url: 'https://api.github.com/user/starred/' + url,
                dataType: 'json',
                async: false,
                headers: headers,
                success: function (data, textStatus, request) {
                    console.log(url + ' - starred');
                }
        });
};

function copyStars(username, password, stars) {
    var headers = {
        "Authorization": "Basic " + btoa(username + ":" + password)
    }

    $.when.apply($, stars.map(function(star) {
        return starRepo(star, headers);
    })).then(function() {
    // all ajax calls done now
        console.log('done');
    });
}

var username = 'user'; // YOUR username 
var password = 'pass'; // YOUR password
var githubUser = ''; // the github user you wish to copy the stars from
var copyToUsername = 'copyUser';  // Destined username to copy the star to
var copyToPassword = 'copyPass'; // Destined user password```

edit the details of the users above and paste it to the console. 
first you need to copy the stars:
`var stars = fetchStars(username, password, githubUser);`
after the above is finished, run the copy command, that will make the new user have those stars
`copyStars(copyToUsername, copyToPassword, starsArr);```

Thats it, thats how i did mine.

**Comment by syropian** [comment]
Thank you! This is very helpful, and should be useful for performance testing. Much appreciated!

**Comment by syropian** [comment]
Closing for now.
