### ISSUE TITLE
Initial Page Load is slow

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#108]
With many stars, the astral dashboard is very slow to load.

A possible way to improve this is to fork off jobs on a queue to obtain the users stars.

We can get the number of stars a user themselves have.

<details>
`curl -I https://api.github.com/users/pantchox/starred?per_page=1` gives us the following headers as part of its response:

```
Link: <https://api.github.com/user/7011604/starred?per_page=1&page=2>; rel="next", <https://api.github.com/user/7011604/starred?per_page=1&page=1558>; rel="last"
```

Where we can quite easily parse to get the page number of the `last` rel. From there, because there is only one per page, we can get that the user has `1558` stars.

Now, we can queue up `1558 / x` jobs, to get them all primed for the cache.

It might be worth us storing this value on the user itself.

The response will always have  the last tag, unless there is 0 or 1 star.

If there are 0, then the request we receive will be empty, if the user has 1 star, then the star will be within the request itself.
</details>

Reported by @pantchox in #107

**Comment by syropian** [comment]
Like the idea of using a queue! I've never used them before so I'll leave that in your hands :D
