### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by mistadikay** [astralapp/astral#117]
Exception while trying to load the stars. Chrome Version 54.0.2840.98 (64-bit), macOS
![screenshot 2016-11-27 12 30 40](https://cloud.githubusercontent.com/assets/742056/20648078/7da77896-b49d-11e6-9d8d-8701729b3539.png)

**Comment by syropian** [comment]
Any steps to reproduce? I know this sometimes happens right before the app reauthenticates you, or on the odd time that authentication randomly fails. Usually just refreshing fixes it.

**Comment by mistadikay** [comment]
Hm, can't reproduce anymore. I had this bug while `https://app.astralapp.com/dashboard` page was loading, refreshing didn't help, but now it seems to be fine.
