### ISSUE TITLE
Ability to edit tag directly at the tag list column

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#12]
_From @enginebai on January 20, 2015 1:7_

Hi, is it possible edit the tag directly at the tag list column?? Thanks.
![2015-01-20 8 59 38](https://cloud.githubusercontent.com/assets/3387462/5810575/a000a794-a083-11e4-946c-7da3119d2322.png)

_Copied from original issue: syropian/astral-issues#26_

**Comment by syropian** [comment]
_From @thasmo on January 23, 2015 22:5_

Double-click or long-press would be nice.

**Comment by syropian** [comment]
Been thinking of a nice way to do this without cluttering the UI. Double-click would be fine, but non-obvious for a lot of people.

**Comment by maxailloud** [comment]
Maybe a button on the top list to make the list in edition mode, and then you can edit/delete tag.
And in edition mode you can add a checkbox in front of each tag to allow mass deletion.

**Comment by solygen** [comment]
Small edit icon that is shown for each tag only on hover. Perhaps positioned on the left of the badge/count.

**Comment by muescha** [comment]
this small icon can be the same like on top of the page beside the tag name where i can edit the tag
