### ISSUE TITLE
Laravel mix instead of elixir

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#124]
Laravel mix seems to be the future using webpack rather than elixir. Worth moving over?

**Comment by syropian** [comment]
Yeah, I think I'll end up switching to Mix. I've also made some decent progress upgrading from Vue/Vue-Router/Vuex v1 -> v2.

**Comment by alexbowers** [comment]
This is the only thing I didn't update when doing the 5.4 PR check, i'll leave it in your hands

**Comment by syropian** [comment]
Now uses Mix!
