### ISSUE TITLE
Hide/Show option for language tags

### ISSUE THREAD

**Issue by JohannesMP** [astralapp/astral#126]
While the `Auto-Tag by Language` option in Settings is great, it does tend to clutter up the list of tags a bit. It's useful information, but I do value tags I create myself more than language.

It would be nice if it was possible to hide these auto-generated language tags from the left sidebar. A checkbox for 'show language tags' would be ideal.

Alternatively, this information could be exposed without actually generating the tags. Call them 'meta tags' or something similar to differentiate them. It's data that is extracted from a repo's metadata anyways, so displaying it without creating actual tags should be possible.

**Comment by syropian** [comment]
Thanks, I'm going to close this since you went into more detail in #127
