### ISSUE TITLE
Meta Tags

### ISSUE THREAD

**Issue by JohannesMP** [astralapp/astral#127]
# Overview

I alluded to this in issue request #126, but I think it would be useful to view some meta information from Github repos in a way that is similar to user-defined tags, but without permanently storing them, so that they could update over time.

[Github recently introduced topics ](https://github.com/blog/2309-introducing-topics), a mechanism for adding categories/tags to repositories. For example, the astral repo itself is already using topics:

![j7jyxsa](https://cloud.githubusercontent.com/assets/662874/23578848/d87d6daa-0094-11e7-95a9-d69838a0e228.png)

If I star the astral repo, it would be really useful to have these pre-defined topics show up in the left sidebar in addition to my user-defined tags, as well as on the small repo preview card.

However it would not make sense to automatically import them, like the `Auto-Tag by Language` Settings feature currently does. If a repo's topics are changed, I'd want the topics to update accordingly.

# Mockup

Here is a quick Mockup of what this could look like:
![ok1rqq4](https://cloud.githubusercontent.com/assets/662874/23578942/ce40c3ee-0096-11e7-8cfe-8b2162a29d23.png)
- Language meta-tags are green
- Topic meta-tags are red
- User-defined tags are blue

# Proposal

So Here is the general proposal:
- A repository's language and topics should be extracted when stars are imported. They would be considered 'meta tags'
- By default meta tags appear in the tags section, and can be sorted the same way
- Meta-tags should be visually differentiated from user-created tags. 
  - As in the mockup, color could be used to differentiate them.
  - Alternatively, they could have a different icon before them (more color-blind friendly as well)
- The visibility of meta tags in the left sidebar could be toggled, in case a user only wants to see their own tags. Ideally this would be a checkbox accessible in the sidebar, maybe under 'sort'.
- Meta-tags could also be completely disabled via a setting. This would hide meta-tags everywhere, including the repo preview card.
- Unlike user-created tags, they do not show up in the 'Edit Tags' UI when a repo is inspected.

**Comment by syropian** [comment]
Thanks! These are some great ideas, and I've had similar thoughts floating around about tags as well. I'm in the middle of upgrading the front end to Vue 2.x, and refactoring the Vuex store so I've got that to finish, but I think this is the next thing I'll tackle. Cheers!
