### ISSUE TITLE
Tag length prompt blocks save button

### ISSUE THREAD

**Issue by JohannesMP** [astralapp/astral#128]
When removing a tag in the `Edit Tags` UI by clicking the 'x' on the tag, the prompt to "enter 2 or more characters" blocks the `SAVE TAGS` button.

Additionally, if the user clicks on that prompt, the UI will hide, but the prompt will remain visible:
![animation](https://cloud.githubusercontent.com/assets/662874/23579034/1d09f3fe-0099-11e7-8f9c-a1704b0ba4cc.gif)

It's a minor gripe, since by clicking in the text box the prompt disappears, but it would be nice if the save button could be clicked without having to do that each time I want to remove a tag.

**Comment by syropian** [comment]
Yeah, this is a weird side effect of the library I'm using. I'm hoping to replace it with something new soon!
