### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by dnepro** [astralapp/astral#130]
According to Cloudflare and the provided error message (Error 526), the cause is a "Invalid SSL certificate".

**Comment by syropian** [comment]
Yup, it's related to: https://twitter.com/laravelphp/status/843173647846195201 (and https://twitter.com/laravelphp/status/843173737830780929). The server is unable to re-issue certs at the moment, so unfortunately we just have to wait it out.

**Comment by dnepro** [comment]
Ok i see, thank you for responding so fast!
Really like astral and by this opportunity, would like to thank you 👍

**Comment by syropian** [comment]
@dnepro Thank you! I'm really glad you like it :D
