### ISSUE TITLE
Show the repo's last update date

### ISSUE THREAD

**Issue by Romainpetit** [astralapp/astral#132]
The way I use Github Stars is the following : I add everything of interest, then I come back and **drop everything from the list that hasn't been updated** for 6 months. 

I'd love to see this in various parts of Astral : 
- As a displayed information in the repo's list
- As a filter in the repo's list sorting dropdown ( most recent update first, oldest update first )
- As a displayed information in the repo's detailed view

For now, the information is nowhere to be found in the app. So for sorting my stars with Astral means a lot of back and forth between Github and Astral ...

**Comment by schmurfy** [comment]
I know this issue was open a long time ago but I would love to see that as well.
is it feasible ?

**Comment by tomershvueli** [comment]
I would also like to see this update! @syropian If I were to put in a PR to display the last updated date of a repo, would you consider merging it in?

**Comment by syropian** [comment]
@tomershvueli For sure, I'll take a look when it's ready!

**Comment by tomershvueli** [comment]
@syropian check out PR #332, notes welcome.

**Comment by tomershvueli** [comment]
So with #332 and #333 the Updated Date is now in the list and in the repo details. Sorting doesn't exist yet.

**Comment by Romainpetit** [comment]
Great job @tomershvueli 🙏 !
