### ISSUE TITLE
[bug] duplication of project list

### ISSUE THREAD

**Issue by mrdulin** [astralapp/astral#134]
![](https://ws1.sinaimg.cn/mw690/005FHMJXgy1fe75dpu6i4j30ma1p8tf5)

**Comment by syropian** [comment]
Hm, I haven't come across this, but you can try refreshing your stars to fix it. ![](http://d.pr/i/OOMX+)

**Comment by mishizuo** [comment]
same duplicated list and can't edit tag name from yesterday
