### ISSUE TITLE
[enhancement] Implement SweetAlert

### ISSUE THREAD

**Issue by bntzio** [astralapp/astral#136]
Hello @syropian, nice work on astral!

I noticed that the app shows default browser alerts (deleting a tag), what do you think about implementing [SweetAlert](https://github.com/t4t5/sweetalert) to improve the design? 

I'll be happy to submit a PR. 😃

**Comment by syropian** [comment]
I'd be happy to accept a PR. One note is, instead of showing a follow-up success SweetAlert, just close the modal after they confirm they want to delete as there's already an existing notification module that indicates success or failure.

**Comment by bntzio** [comment]
@syropian I got an error when trying to run the app.

![error](https://cl.ly/k3hu/Screen%20Shot%202017-04-19%20at%203.40.27%20AM.png)

Why is that? Also, when trying to do:

`php artisan migrate`

I get the following errors:

![error2](https://cl.ly/k3wZ/Screen%20Shot%202017-04-19%20at%203.42.59%20AM.png)

**Comment by bntzio** [comment]
Here's my Github's OAuth App settings:

![oauth](https://cl.ly/k3li/Screen%20Shot%202017-04-19%20at%203.44.10%20AM.png)

And here's my `.env` file:

![dotenv](https://cl.ly/k45e/[54fa0c0e54191f2908d479c5c057cae6]_Screen%20Shot%202017-04-19%20at%203.44.28%20AM.png)

**Comment by alexbowers** [comment]
The database doesn't exist.

Either change the database to be sqlite, or create the database in mysql and change the database details to be correct `DB_DATABASE`, `DB_USERNAME` and `DB_PASSWORD`.

**Comment by bntzio** [comment]
@alexbowers Ok so I got it running now, I used homestead instead, now I got another problem, I can't build the js/css neither w/webpack or gulp.

What I did was a simple change to a vue component, but I need to watch for that changes and compile the js, I tried with `npm run watch` and `npm run dev` but none worked.

Also, I tried using `gulp` and `gulp watch` and it appeared that some packages weren't installed (like gulp-notify, karma, laravel-elixir, and so on) 🤔.

I installed those dependencies with `npm i --save-dev` and the gulp worked.

The thing is, when I go to astralapp.app I see this error message:

**Unable to locate Mix file: /css/app.css. Please check your webpack.mix.js output paths and try again. (View: /home/vagrant/astral/resources/views/index.blade.php)**

I don't know why I can't compile js/css, how do you do it?

I already did `npm install` as mentioned in the readme so everything should properly work without any issues, but it isn't working for me.

**Comment by bntzio** [comment]
I think something is wrong with the mozjpeg package, when I do a `npm install` I get this:

![](https://cl.ly/k7rm/Screen%20Shot%202017-04-21%20at%201.49.20%20PM.png)

Then all dependencies installs normally.

And when I do `npm run dev` or `npm run watch` I get this:

![](https://cl.ly/k7Nd/Screen%20Shot%202017-04-21%20at%201.44.55%20PM.png)

That's why I can't handle the js/css compilation using webpack, so I tried gulp but as mentioned earlier, I got errors, the easier way I think, is using webpack, but this error appears.

**Comment by syropian** [comment]
gulp is no longer used, it's all Laravel Mix. What's your node and npm version?

**Comment by bntzio** [comment]
node: v6.4.0
npm: 3.10.3

**Comment by syropian** [comment]
Do you have `nvm` installed? I'm currently using 7.3.0 myself. Not sure if that's the problem or not.

**Comment by syropian** [comment]
I just blew away my `node_modules` folder and ran `npm install` and everything worked fine for me.  

OS: `macOS 10.12.4`
Node: `7.3.0`
npm: `3.10.3`

**Comment by bntzio** [comment]
Yep, I do. I just installed 7.3.0 and ran `npm run reinstall-deps` same error.

**Comment by bntzio** [comment]
Mmm... what could it be. When you run `npm run dev` aren't u getting errors?

**Comment by syropian** [comment]
Nope, not getting any errors at all.

**Comment by syropian** [comment]
@bntzio Are you using homebrew? Check that your copy of libpng is linked properly.

```
brew link --overwrite libpng
```

**Comment by bntzio** [comment]
Yes, I'm into it.

Are you using webpack 2?

**Comment by syropian** [comment]
afaik Laravel Mix uses webpack 2 by default.

**Comment by bntzio** [comment]
@syropian I got it working now! 🎉 the problem was with `libpng`.

Solution:
1) `brew install libpng`
2) `brew link libpng`

Just as you mentioned earlier 👍 

It seems that some people are having problems with this as well -> [unable to load image files issue](https://github.com/tcoopman/image-webpack-loader/issues/51)

**Comment by bntzio** [comment]
Now when I run `npm run dev` everything works fine.

Thank you for ur time @syropian 

Now I'll go back to implement the SweetAlert.

**Comment by syropian** [comment]
Awesome! Really glad you got it sorted, it's good to have these issues in the open in case anyone runs into something similar. Cheers!

**Comment by bntzio** [comment]
PR ready! 😄 #138

**Comment by syropian** [comment]
Added in #138 🎆
