### ISSUE TITLE
Previous tags are shown for the next selection

### ISSUE THREAD

**Issue by Ibrahim-Islam** [astralapp/astral#137]
![prob](https://cloud.githubusercontent.com/assets/6401874/25270423/7cde958a-26a2-11e7-929a-89a9dc6f9bb7.png)

As can be seen from the above screenshot, when I add tags to a repo and move immediately to the next one which is without a tag then the tags are shown for the previous repo rather than the current selected ones'.

**Comment by syropian** [comment]
@Ibrahim-Islam Hm, I was not able to reproduce this. Can you make sure my steps were correct?

1) Clicked a repo with no tags, added one tag to it.
2) Clicked the repo above it that also had no tags, opened tag dropdown.

**Comment by Ibrahim-Islam** [comment]
@syropian Yes those were the steps with emphasis on switching very fast from step 1 to 2.

**Comment by syropian** [comment]
Thanks, I have a branch in the works that totally replaces the current tagging library for my own lightweight implementation. I'll look out for this issue.

**Comment by pantuts** [comment]
Same here.

Other issue is:
Tags: security, python, test
and then user go to `security` tag and edit the tag of selected repo, add 1 or more tags, the new tag(s) will only be saved, excluding the previous tag(s) the the repo has.

**Comment by proweb** [comment]
confirm

**Comment by syropian** [comment]
I'm working on a new version of Astral that reworks how tags are edited (you can edit them right on the repo itself instead of clicking into it). I probably won't work on a fix since I'm dedicating all my time to the new version at the moment, and this is a little edge-case-ish.

**Comment by DeveloperPaul123** [comment]
I experienced the same behavior but the difference was the tag I added did not exist when I added it. So it was being created when I tagged the first repo. Then when I moved on to the next repo, the tag I had previously created was still in the tag box.

**Comment by egomadking** [comment]
A quick work around that I found when organizing tags on Astral: As soon as I edit tags on a repo, I refresh the page. It takes a fraction of a second to reload and the tags don't follow me when I attempt to edit the next set of tags on another repo. It sucks to refresh, but Astral is well worth it for the value it brings to bear.

**Comment by lacymorrow** [comment]
Huge bug and likely related, it seems that sometimes on "saving", incorrect tags are attributed to the next repo.

**Comment by spencermathews** [comment]
I can also confirm this behavior. As @DeveloperPaul123 mentioned it seems to be only newly added tags that carry over to to the next item(s). I would say it's more than an edge case, however. Thanks for this excellent tool!

**Comment by syropian** [comment]
Locking this thread. There's plenty of confirmation that the issue exists, and I mentioned tags are fully reworked in v3 thats on the way. As such I'm not committing any more fixes to this version.
