### ISSUE TITLE
README Images not showing up in README preview on the app

### ISSUE THREAD

**Issue by thundergolfer** [astralapp/astral#139]
The repo that I discovered this on was https://github.com/thundergolfer/arXie-Bot. You can see in the screenshot below that the header image is not available. 

![image](https://cloud.githubusercontent.com/assets/12058921/26334624/a0f89a2c-3fa9-11e7-8d96-779a503d67b1.png)

The README.md markdown that is supposed to link the image looks like this: 

```
<p align="center">
  <img src='images/arXie_300.png'/>
</p>
```

where the image~s~ is hosted locally in the repo.

**Comment by syropian** [comment]
Thanks, we do have a regex in place that's supposed to catch this. Will take a look within the next couple days!

**Comment by runofthemill** [comment]
Here's another repo where it's happening:
https://github.com/zyedidia/micro

<img width="1552" alt="screen shot 2018-10-02 at 9 02 56 pm" src="https://user-images.githubusercontent.com/8418440/46389429-8d19dd80-c686-11e8-8aa7-da87fc1fa88b.png">

Image source:
```<img src="./assets/micro-solarized.png" alt="Screenshot" style="max-width:100%;">```

**Comment by syropian** [comment]
Thanks! I've put this off for quite a while, hoping to dig into it soon.
