### ISSUE TITLE
Ability To Share My Tags?

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#14]
_From @Gerst20051 on January 30, 2015 0:20_

@syropian is this on the radar?

_Copied from original issue: syropian/astral-issues#29_

**Comment by syropian** [comment]
Yep, definitely on my radar, just hoping to squash a few bugs and UX problems first, and then I can move on to more features :)

**Comment by syropian** [comment]
_From @hlfcoding on March 11, 2015 8:45_

In the meantime, you can run script below in the console directly in the app.
```js
// build repos
var repos = $('.repo').map(function(){
  var $el = $(this);
  var name = $el.find('.repo-name').text();
  var tags = $el.find('.repo-tags li').map(function() { return $(this).text(); }).get();
  return { name: name, tags: tags };
}).get();
JSON.stringify(repos);
// build tags from repos
var tags = [];
_.each(repos, function(repo) {
  _.each(repo.tags, function(name) {
    tag = _.findWhere(tags, { name: name });
    if (tag === undefined) {
      tag = { name: name, repos: [] };
      tags.push(tag);
    }
    tag.repos.push(repo);
  });
});
JSON.stringify(tags);
```
If you don't mind bookmarklets, there's also tools like, which will at least simplify part of the above: http://medialab.github.io/artoo. Anyway, the above allows finding repos by multiple tags, currently not possible in the app:
```js
JSON.stringify(_.intersection(_.findWhere(tags, { name: 'referrable' }).repos, _.findWhere(tags, { name: 'ios' }).repos));
```

**Comment by desmondmorris** [comment]
+1

**Comment by smithln** [comment]
+1

**Comment by syropian** [comment]
@desmondmorris @smithln Thanks you two! This will be implemented in the rewrite :)

**Comment by hlfcoding** [comment]
Thanks for implementing! :+1:

**Comment by pfalcon** [comment]
Ok, in the current https://app.astralapp.com/ , there's Settings -> "ENABLE CROWSOURCED TAGGING BETA". But after enabling it, I don't see any changes in my tags. I have 2+K stars projects in my starred, so I'd assume at least one would be tagged, if Astralall has any userbase at all. So, how is that supposed to work?

**Comment by syropian** [comment]
@pfalcon Unfortunately it doesn't always work, as it hits the servers really hard. I'm hoping to write a better solution in the future, though i'm not quite sure what it is yet.

**Comment by syropian** [comment]
@pfalcon you could try refreshing though.

**Comment by pfalcon** [comment]
Thanks for hint, after couple of page reloads, seeing "Crowd-tagging Stars..." progress indicator...

**Comment by pfalcon** [comment]
... but nothing happened after 2 hours of waiting (but then I have 700+ starred projects, which probably on a higher side).

**Comment by Gerst20051** [comment]
same thing here. just a loading indicator.

**Comment by syropian** [comment]
The server probably just gave up at this point ¯\_(ツ)_/¯

**Comment by Gerst20051** [comment]
love that emoticon!!
