### ISSUE TITLE
Tags return no stars

### ISSUE THREAD

**Issue by akazorg** [astralapp/astral#148]
I can't see any starts when I select any of the tags.
Is this a bug?

Thank you!

**Comment by syropian** [comment]
Hi Bruno, I'm unable to replicate this issue on production. Are you getting any errors in the console?

**Comment by akazorg** [comment]
Hi Collin, no errors in the console.
Adding new tags works normally, but all previous tags are empty.

I had an issue a couple of days ago with my computer date changing to the past, tried to replicate it but the issue is not related to that.

For debug proposes, I added a tag named `Laravel` and related some repos with it. This is the only tag with related stars, all other tags are empty.

I'm curious how they vanished. Any tip on how to debug this?
Thanks

**Comment by syropian** [comment]
@akazorg This actually isn't the first case I've heard of tag entries disappearing but I'm honestly not sure what the cause is yet. I may have to create a a more isolated test account to try and figure out why/when it happens.

**Comment by akazorg** [comment]
Thanks for the reply Collin. I'll use the search for now.
Good luck with that.

**Comment by syropian** [comment]
@akazorg If you wanted a way to help me determine if the cleanup step is the problem, tag a few stars that you had tagged before, and then refresh the page. While the initial data is loading (the status text will say `Loading Stars`) your tags should be there, and then it will change to `Cleaning up`. If the tags suddenly disappear after that cleanup step we'll know it's the culprit.

**Comment by akazorg** [comment]
@syropian sure, I'm glad to help! :)
Unfortunately, following that steps, tags don't disappear. I've also monitored the console and found nothing suspicious. Tried changing the date, using the same steps, and still, all working properly.

**Comment by syropian** [comment]
@akazorg Super weird! I'll keep an eye out for this happening in the future, though it seems to be a little fleeting.

**Comment by akazorg** [comment]
Thanks, I'll play around with it and let you know of something come up.
