### ISSUE TITLE
Able to duplicate tags

### ISSUE THREAD

**Issue by CrystalDave** [astralapp/astral#17]
Currently, I have an older "Tool" tag, and the newer, crowdsourced "Tools" tag. I wanted to merge them, so I tried renaming "Tool" to "Tools", figuring that worst-case, it'd pop up an error message and I'd have to do so manually.

Instead, now there's two different "Tool" tags. Ideally (in my mind, at least), it'd detect the overlap and offer to merge the tags.

**Comment by syropian** [comment]
I think instead of merging functionality, simply having multi-select (with select all etc.) would make this kind of thing easier.
