### ISSUE TITLE
count badges for tags is not working consistently

### ISSUE THREAD

**Issue by adalisan** [astralapp/astral#209]
I can add a screenshot for this later on.

**Comment by syropian** [comment]
Yeah, some context, repro steps would be appreciated 😅

**Comment by adalisan** [comment]
![image](https://user-images.githubusercontent.com/1790714/44130967-f52c8e7a-a01d-11e8-94da-d3733089a777.png)
For example the label non-code has about 10 tagged repos. No badge is shown
Also the tag icon to the left of labels are not aligned.

**Comment by syropian** [comment]
Thanks! The styling issue should be a fairly easy fix. The count issue seems like a weird one, I’ll be sure to look into it.

**Comment by syropian** [comment]
@adalisan Are your `non-code` tags actually persisting on refresh? Oddly enough I did a search through the DB and while I found your tag, I do not see any stars associated with it.

**Comment by syropian** [comment]
@adalisan This is slightly annoying but could you remove your non-code tag from all your stars and try again? I just pushed a fix.
