### ISSUE TITLE
Notes Editor is buggy and does not work

### ISSUE THREAD

**Issue by adityamenon** [astralapp/astral#210]
<img width="1270" alt="screen shot 2018-08-12 at 11 25 53 am" src="https://user-images.githubusercontent.com/640815/43998190-8a4f82b2-9e22-11e8-98c6-c4fbf03306a5.png">

When I try to add or edit notes to the repositories on Astral, I'm seeing errors that are attached in the logs. I can't really edit any of the text, and once the Notes tab is open, I can't switch between repositories either.

[app.astralapp.com-1534044404254.chrome.log](https://github.com/astralapp/astral/files/2280700/app.astralapp.com-1534044404254.chrome.log)

**Comment by syropian** [comment]
Whoops, looks like a regression of some kind. Will get a fix out soon!

**Comment by syropian** [comment]
This actually looks like a strange issue with CodeMirror (which the Markdown Editor uses under the hood). One of its helper functions is (somehow failing), even though when I set a breakpoint on it, all the values looked fine.

**Comment by adityamenon** [comment]
@syropian I'm working in the `Guest` mode of Chrome - might it have anything at all to do with Cookies or Privacy Settings?

**Comment by adityamenon** [comment]
Hmm - no. I tried on the primary laptop screen. Same errors, and the notes are not getting saved.

**Comment by adityamenon** [comment]
![screen shot 2018-08-12 at 8 57 13 pm](https://user-images.githubusercontent.com/640815/44002242-565fde70-9e72-11e8-98ce-ff86c4aa8739.png)
