### ISSUE TITLE
Case insensitive sorting of tags

### ISSUE THREAD

**Issue by farant** [astralapp/astral#216]
This is a really cool project! 

At the moment tags in the sidebar are sorted with uppercase letters having a higher precedence than lower case letters. So tags beginning with a capital letter are at the top followed by tags beginning with a lower case letter. 

It would be nice if the sorting was case-insenstive throughout the word. If all tags could be sorted based on their lowercase version for example.

**Comment by syropian** [comment]
Good catch, will get this fixed soon 👍

**Comment by syropian** [comment]
Fixed in 58a9b24
