### ISSUE TITLE
Link to github repo from the website

### ISSUE THREAD

**Issue by rpowis** [astralapp/astral#22]
To make it easier for people to report issues and contribute :)

**Comment by syropian** [comment]
Thanks! I will certainly be doing this when v2 beta is released.

**Comment by rpowis** [comment]
Cool! Look forward to it. In the meantime I'm keen to help out as per the README's Todo section

**Comment by syropian** [comment]
@rpowis Thanks! I'm currently rewriting a bunch of the core stuff (I found trying to simply upgrade to L5 was causing me to frankenstein things), and I'm also planning to move the whole front-end away from Angular to RiotJS. The current state of this repo is fairly out of date at the moment, but I plan on getting the WIP pushed up here soon. Once that's done I'd love any help you're willing to spare ^_^

**Comment by rpowis** [comment]
Sure! Sounds good. Perhaps setting up a [gitter.im](https://gitter.im/) room (and adding the badge to the README) might help with throwing ideas around?

**Comment by syropian** [comment]
@rpowis For sure, I set up a Gitter room just now :)
