### ISSUE TITLE
notes save button instead of autosave?

### ISSUE THREAD

**Issue by tarol** [astralapp/astral#221]
If i use input methods (e.g. Chinese input method) .
Now i input 'shi', when i choose the word, the editor will save 'shi'. 
Then i choose '是',  'shi' will be replaced by '是'. 
After that, the save request has been responsed, and editor will commit the action named SET_STAR_NOTES, so 'shi' will replace '是'. 
At last, i get 'shi' but not '是'.

**Comment by syropian** [comment]
Interesting! I never considered such input methods. I think I’ll keep autosave for now, but I’ll also include a manual “Save” button too.

**Comment by tarol** [comment]
Or cancel the sync after respond.
