### ISSUE TITLE
close note autosave

### ISSUE THREAD

**Issue by zuiyangqingzhou** [astralapp/astral#229]
How can I just close note autosave? 
because I do want to see  frequent pop-ups  to tell me 'note saved' when I type some notes，I just need the notes save button to save notes.

**Comment by syropian** [comment]
I’m not 100% sure what you’re asking, but you can’t currently turn off note auto-saving.

**Comment by zuiyangqingzhou** [comment]
Thank you for your reply. I have successfully deployed the code on my own server, but When I record notes in Chinese, auto-saving often causing input problems, just like #221 , so I want turn off note auto-saving, just use save button.

**Comment by syropian** [comment]
Even if the auto-save is not saving the correct contents, manually hitting the Save button should be though right?

**Comment by zuiyangqingzhou** [comment]
First of all, thank you for your patience. 
Yes, the save button is right, so I  am very much looking forward that you can  add a setting to toggle it off. 
Forgive my lame English, I hope you can understand what I mean.

**Comment by syropian** [comment]
No problem, your english is fine!

**Comment by zuiyangqingzhou** [comment]
Haha, thank you for your compliment, I will close the issue.

**Comment by syropian** [comment]
@zuiyangqingzhou You can now turn off notes auto-saving in your Settings panel 😄

**Comment by zuiyangqingzhou** [comment]
I am astonished by your efficiency, I have tried it with excitement, everything is ok now. show you respect
