### ISSUE TITLE
Whoops, something went wrong on our servers.

### ISSUE THREAD

**Issue by w00p** [astralapp/astral#241]
Hi. When i try to log in on https://app.astralapp.com i get a error 500. Any clue?

**Comment by syropian** [comment]
Hi, thanks for reporting! I actually had an unchecked log file that was eating up almost all of my server's space, so things were slowly shutting down 😅 

Should be fixed now, let me know if you have any further troubles.

**Comment by w00p** [comment]
Awesome work man! Work fine now :D thank you!
