### ISSUE TITLE
Editing tags has wrong UX. Comma should not be required before hitting Enter key.

### ISSUE THREAD

**Issue by przemoc** [astralapp/astral#243]
When I click Edit Tags, write tag name and hit Enter, editing box disappears and no tag is added.
I have to write comma before hitting Enter, which is completely unintuitive.

**Comment by przemoc** [comment]
If tag name refers to an existing one, then completion shows up, so Enter does the job.
The issue is observed when we're creating new tags, which is a common use case for new users.

**Comment by syropian** [comment]
@przemoc Thanks, this should be a relatively easy fix.

**Comment by syropian** [comment]
Fixed in 8cb2723ee9c81ba0e13154756907d203b2920655
