### ISSUE TITLE
Added tags can be lost when session timeouts

### ISSUE THREAD

**Issue by przemoc** [astralapp/astral#244]
I experienced it once so far, so cannot provide exact details, but I added 2 tags (1 for one project, 1 for another project), the tab in browser was left untouched for longer time and when I logged back again, the tags weren't there.

**Comment by syropian** [comment]
That sounds a little suspicious, as soon as you blur out of the editor or hit "Enter" tags are immediately saved on the backend. If you mean you added some tags in the editor without saving, then refreshed, and they were gone well...that would happen regardless of session state 😅 

I think I'll close this in favour of #246 which covers a more generic case of session timeouts and their caveats.
