### ISSUE TITLE
Session should not timeout when site is actively used

### ISSUE THREAD

**Issue by przemoc** [astralapp/astral#246]
I just experienced astral start screen with sign-in button in the middle of editing tags.

**Comment by syropian** [comment]
Yeah, I got a little lazy with the auth mechanism, where I'm skipping fetching refresh tokens, and just always let the JWT TTL expire, and then force a manual reauthentication. I'm going to be getting Astral updated to Laravel 5.8, which is pretty much just waiting on the `jwt-auth` package to become compatible, so I'll probably look into this shortly after the upgrade, as it's pretty annoying.

**Comment by syropian** [comment]
Fixed in #254
