### ISSUE TITLE
Adding tags doesn't seem to work

### ISSUE THREAD

**Issue by przemoc** [astralapp/astral#255]
Using Edit tags, inputting tag name, hitting Enter once, and then second time, doesn't lead to truly adding the tag. It is only shown in UI until chosen category/tag isn't changed.

Please check following animated gif:
![example](https://i.imgur.com/5BLJnMx.gif)

**Comment by syropian** [comment]
Hm, I just tried this myself and it worked just fine. Any console errors?

**Comment by przemoc** [comment]
No errors. Did you test existing using tag name?

It seems that UX is different (so I suggest fixing it too) when using existing tag vs non-existing tag.
When it doesn't exist, one Enter is enough, i.e. it lefts whole editing tags UI. And tag is indeed added.
When it does exist, I need to press Enter second time, because first time it only confirms tag name (adds it to the list) and I remain in editing tags UI.

**Comment by syropian** [comment]
Yes, I tried testing with an existing tag, just like you did. 

The UX is intentionally different, because you need to hit enter to confirm the autocomplete item of an existing tag vs adding a new arbitrary tag. 

Here's a GIF of it working correctly:

![Kapture 2019-03-30 at 15 56 31](https://user-images.githubusercontent.com/749061/55281023-7b975280-5304-11e9-98b3-5ba0625c3a83.gif)

**Comment by przemoc** [comment]
Ok, I have no idea why it works for you, while it doesn't for me.

(Regarding UX, when tag exists, you can add more tags, because you're not leaving Editing Tags UI, but when tag doesn't exist, you need to click Edit Tags again. I kind of like 1-Enter, but it makes UX inconsistent, so I think Enter for completely new tags should work more like comma, allowing user to input more tags.)

Oh, after some much longer time it actually started showing up in given tag (I was visiting the page again, though). I know you'll want to close it now, but I think I witnessed same thing in the past. And I'm experiencing it again with another entry and other tag.

**Comment by syropian** [comment]
Closing for now but I'll keep an eye out for this

**Comment by franky47** [comment]
I have had issues entering tags, and by looking at the network tab in devtools, the operation is not commited (`PUT /api/star/tags`) when validating the list of tags with Enter. It is commited when clicking anywhere else in the UI though, which makes quick tag edition difficult using combinations of Tab + Enter.
