### ISSUE TITLE
Feature request: Versions and outdated notices

### ISSUE THREAD

**Issue by selfagency** [astralapp/astral#259]
It'd be awesome if you could add to the list view the current release number of the repository as well as some kind of indicator to let you know whether the project hasn't been updated in over a year or whether it's been archived by the owner. Something like this maybe? You could also save some real estate by replacing the `View on Github` link with an icon.

![Screen Shot 2019-06-07 at 11 35 04 PM](https://user-images.githubusercontent.com/2541728/59141684-9aa70600-897f-11e9-88af-e5be7919d68c.png)

**Comment by syropian** [comment]
👍  This would be a nice update for sure!

I'm probably going to be livestreaming some Astral work at some point this week, and I think it would be a good item to include. Thanks!

**Comment by selfagency** [comment]
Sweet. A couple more ideas related to this: Maybe add a link in the sidebar to view all outdated repos.

And bring. back. unstarring. 😉

**Comment by syropian** [comment]
Ha, the reason unstarring is gone is mostly due to how bad GitHub's OAuth permissions are. Essentially I can't add unstarring without requesting full read/write access to the user's repos, which is less than ideal.

**Comment by selfagency** [comment]
Hrm, are you sure that's still the case? The API docs only say the user needs to be authenticated, not that you need full access to their own repos. 

```
Unstar a repository
Requires for the user to be authenticated.

DELETE /user/starred/:owner/:repo
```

**Comment by selfagency** [comment]
Scope docs says you already need full access to public repos for starring.

```
public_repo | Limits access to public repositories. That includes read/write access to code, commit statuses, repository projects, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.
```

**Comment by selfagency** [comment]
Obviously you know better than me but I'm just wondering if that's changed at all.

**Comment by syropian** [comment]
Exactly, which means you likely need _at least_ `public_repo` to unstar as well. Remember, Astral pulls down starred repos, but it doesn't actually star them.

**Comment by selfagency** [comment]
That's fair. You could always give the user the option with a privacy warning...

**Comment by selfagency** [comment]
I've feel like I've given much shittier apps much more access.

**Comment by syropian** [comment]
Yeah I think I could add a scope column on the user table and allow them to "upgrade" their permissions to allow for unstarring. I'll certainly look in to it!

**Comment by syropian** [comment]
Versions and archived notices have been added. I'm pushing the concept of "outdated" to a new "custom filters" feature that I will eventually be building.
