### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dry11orange** [astralapp/astral#266]
When open my host url with chrome
Fatal error: Class 'Illuminate\Foundation\Application' not found in D:\user_root\code\github\astral\astral\bootstrap\app.php on line 14

The installation is difficult for me
But I'd love to set up my own server locally

When you release
Could you provide an additional HTTP server side zip?

**Comment by syropian** [comment]
Sounds like something went wrong with your initial installation. Try:
```sh
php artisan clear-compiled
composer dump-autoload
composer install --no-scripts
```

If that doesn't work I would try re-cloning it.

**Comment by dry11orange** [comment]
php artisan astral:install
...
Github Client Callback URL [https://astral.test/auth/github/callback]:
>

Which url should I use as the callback?

**Comment by syropian** [comment]
You can use the default, as long as your local domain is `astral.test`. If not just just change it to whatever your local domain is.

**Comment by syropian** [comment]
Closing since the original issue seems resolved
