### ISSUE TITLE
Search with a combination of multiple tags or keywords

### ISSUE THREAD

**Issue by NexZhu** [astralapp/astral#28]
I love this app a lot, thank you @syropian for creating it!
But I think it will be much, much more useful if one can search with a combination of multiple tags or keywords.
I'd like to help but unfortunately I'm not familiar with either PHP or Vue.js :frowning:
Hopefully this will get implemented.

For those who want to do advanced searching now, I wrote a bookmarklet:

> javascript:(function(){var a=prompt().toLowerCase().split(/\s*,\s*/),b=a.filter(function(a){return!a.startsWith("#")}),c=_.difference(a,b).map(function(a){return a.substr(1)}),d=$(".repo").map(function(){var a=$(this),b=a.find(".repo-name").text(),c=a.find(".repo-tags li").map(function(){return $(this).text().toLowerCase()}).get(),d=a.find(".repo-description").text(),e=a.find(".link a").attr("href");return{name:b,tags:c,description:d,link:e}}).get();d=b.reduce(function(a,b){return a.filter(function(a){return a.name.toLowerCase().includes(b)||a.description.toLowerCase().includes(b)})},d);var e=[];_.each(d,function(a){_.each(a.tags,function(b){tag=_.findWhere(e,{name:b}),void 0===tag&&(tag={name:b,repos:[]},e.push(tag)),tag.repos.push(a)})});var f=c.reduce(function(a,b){var c=_.findWhere(e,{name:b});return _.intersection(a,c?c.repos:[])},d).map(function(a){return'<a href="'+a.link+'">'+a.name+"</a>"}).join("<br>"),g=window.open(null,"Result","width=400,height=400,location=no,menubar=no,status=no,toolbar=no");$(g.document.body).html(f)})();

I used codes from here
https://github.com/astralapp/astral/issues/14#issuecomment-88084867

With this you can do:

![1](https://cloud.githubusercontent.com/assets/4370605/12973602/7f6898ac-d0e8-11e5-866b-a16901b3a641.png)
![2](https://cloud.githubusercontent.com/assets/4370605/12973891/d1d175ee-d0ea-11e5-939d-94131521295f.png)

Here's the code if you want to tweak it:
https://gist.github.com/NexZhu/4f369e0c3fe3f4dd0710#file-astral-advanced-search-js

HTH

**Comment by syropian** [comment]
@nexzhu You can already do this by splitting your terms with `:` in the search box. Eg. `#javascript:#node:some string`.

**Comment by NexZhu** [comment]
@syropian Great! There could be an instruction for that in the readme or somewhere though. I've tried with space and comma as the delimiter and haven't had any luck so I thought it was not supported.

**Comment by syropian** [comment]
@NexZhu Yeah it's a bit of a hidden feature atm, going to look into adding something to hint it in v2
