### ISSUE TITLE
I cant login astral with my github account

### ISSUE THREAD

**Issue by Xianmua** [astralapp/astral#281]
Error in the js console:
![image](https://user-images.githubusercontent.com/30331754/64551234-29ecfc80-d367-11e9-9a12-91c3050d5ea7.png)
when I try to login astral with my GitHub account, the website displays that it's fetching GitHub stars. Then it auto jumps to the "sign-in " page again. I am confused about it...

**Comment by syropian** [comment]
Hm, not sure what's going on, but maybe try going to `https://app.astralapp.com/logout` manually in your browser. If that doesn't work I'll try clearing your auth token and you can try again.

**Comment by Xianmua** [comment]
At first, I try to unstar some repositories on astral，but it doesn't work ... So I unstar some repositories on Github. After I refresh the page,  the contents of GitHub stars on astral still doesn't change...So I revoke the GitHub access of astral and reauthorized it. Then I can't log in my astral account. It seems that the website can't fetch the contents of GitHub stars. When it's trying to fetch the contents, it always auto jumps to the login page. I have tried clearing the cookies and re log in astral, but that doesn't work at all... I am trapped in the dead circle.

**Comment by Xianmua** [comment]
![2](https://user-images.githubusercontent.com/30331754/64575395-3a709780-d3a6-11e9-8872-f8c4d165edf0.gif)
just like this

**Comment by syropian** [comment]
I'm going to clear out your current auth token. I've recently switched some of the auth mechanisms around, and you might have got stuck in a weird state.

**Comment by Xianmua** [comment]
Now it works, thanks for your help :)

**Comment by syropian** [comment]
Awesome! Glad to hear it 😄
