### ISSUE TITLE
UX problem on Firefox Android browser

### ISSUE THREAD

**Issue by seangwright** [astralapp/astral#284]
I am not sure what to tap on or what gesture to use in Firefox for Android browser to see my list of started repos.

Here is a screenshot of what I see after logging in:

![Screenshot_20191006-145406](https://user-images.githubusercontent.com/1382768/66274140-6f5af780-e849-11e9-8aa8-16aba84255a7.png)

I can't zoom out any further and I can't get the left tray to collapse.

I love the idea of this app, I imagine it works fine on desktop.

**Comment by syropian** [comment]
Hey Sean, Astral doesn't currently support mobile devices, since it's a lot of work for very little gain.
