### ISSUE TITLE
refresh Starts BUG

### ISSUE THREAD

**Issue by yaobo-lab** [astralapp/astral#286]
![QQ截图20191101084749](https://user-images.githubusercontent.com/21329253/67995862-b214c180-fc87-11e9-9105-0eb003c74648.png)

when i refresh Starts . it loading all day...

**Comment by k-yaobo** [comment]
I urgently need this thing.

**Comment by yaobo-lab** [comment]
![QQ截图20191106101632](https://user-images.githubusercontent.com/21329253/68262586-ab6abd80-007e-11ea-9458-e66e879aaf0b.png)
![QQ截图20191106101640](https://user-images.githubusercontent.com/21329253/68262588-ac9bea80-007e-11ea-951e-7ddd181eb567.png)

**Comment by syropian** [comment]
I'll try and take a look soon. FWIW this essentially happens every 2 hours by itself.

**Comment by yaobo-lab** [comment]
hi...this bug is For too long . i need you help

**Comment by syropian** [comment]
Like I mentioned, I'll get to it when I have time.

**Comment by syropian** [comment]
Unfortunately I'm having some trouble reproducing your problem. I tried refreshing my own stars and everything was working fine. Could you reproduce the issue once when you can so I can check the server logs?

**Comment by yaobo-lab** [comment]
you can check server logs . i found thant  https://app.astralapp.com/api/stars/github http have a 500 error 
![QQ截图20191113091924](https://user-images.githubusercontent.com/21329253/68724517-bda4a880-05f6-11ea-92c8-087a5646739e.png)
![QQ截图20191113091929](https://user-images.githubusercontent.com/21329253/68724521-bf6e6c00-05f6-11ea-910b-464ac78f1864.png)
![QQ截图20191113091935](https://user-images.githubusercontent.com/21329253/68724524-c1d0c600-05f6-11ea-9c95-efaeba554a63.png)

**Comment by syropian** [comment]
It looks like your access token got stuck in a weird state where the GitHub API thinks it's invalid on refresh. I've went ahead and cleared your current token out, so you'll need to log out, and log back in and I _think_ it should work.

**Comment by yaobo-lab** [comment]
is that ok。it Can run normally。thx
