### ISSUE TITLE
Will it be a version to manage tags for gitlab repositories?

### ISSUE THREAD

**Issue by telco2011** [astralapp/astral#288]
It would be awesome it astral could manage more repositories than Github. Gitlab is a great platform as well.

**Comment by syropian** [comment]
Currently no plans to support GitLab, as I think it's use would be pretty minimal compared to the effort required to support it. (I've never "starred" a GitLab repo in my life 😅 )

**Comment by telco2011** [comment]
As it's said, there is always a first time ;-)
Thanks for your answer.
