### ISSUE TITLE
Forced logging out when creating a tag named "SLAM"

### ISSUE THREAD

**Issue by kjnez** [astralapp/astral#289]
I wanted to create a tag named "slam", and figured out that I couldn't.

**Comment by syropian** [comment]
Do you mean a tag? I am able to create one named `slam` no problem

**Comment by kjnez** [comment]
Yes, it's the tab. I still have this problem, though. I'm testing using Firefox in Linux. Whenever I create a tag named "SLAM" or "slam", I'm logged out.
