### ISSUE TITLE
[Bug] sorting TAGS when there is no defined TAGS

### ISSUE THREAD

**Issue by mglowacki100** [astralapp/astral#293]
I'm new user, so I don't have any tags. 
When I click SORT near TAGS, astralapp goes into "sign in" screen. 
Subseqently pressing "back" on browser, astrall goes back to dashboard but number of "untagged stars" is doubled.
Solution proposal: SORT should appear when at least one TAG is defined.

**Comment by syropian** [comment]
Thanks for the report! This should be fixed now.
