### ISSUE TITLE
Expose a public API

### ISSUE THREAD

**Issue by YerkoPalma** [astralapp/astral#30]
A public REST API would be awesome, and would be helpful for many things. It would help to create different clients. If you build a [chrome extension](https://github.com/astralapp/astral/issues/5) (extension that I'm waiting for long time ago :smile:), or even a mobile app (Github has no official mobile app, so astral app would definitly fill a void there). 

It would also help for other developers to build awesome stuff, for example, if you add [support for gists](https://github.com/astralapp/astral/issues/7), it could be used by [Gistblog](https://github.com/khebbie/GistBlog) or [Vist](https://github.com/vist-service/vist).

So, think about it, I'm not an expert for Laravel, but I think that there are some tools to make an API from your app. It would be great.

**Comment by syropian** [comment]
I definitely want to build a solid API, but I'll be looking for a more experienced developer to join the core team first. I'm slowly realizing Laravel isn't going to get much better if I keep writing all the PHP code for it hehe.

**Comment by andyconlin** [comment]
Hi @syropian! Is there any interest on the dev side for a public API these days? I'd be interested in working on a browser extension for easy access to Astral data while on github.com websites. And if not already planned, would you be open to an API if there was an interested contributor?

**Comment by syropian** [comment]
@andyconlin It's something I've wanted to eventually get to, but I haven't dug into the research on how to build a proper public API yet. If you do know of an interested contributor, please feel free to point them my way, I'd be happy to work with someone who has more experience than my building APIs 😅
