### ISSUE TITLE
Forced logoff immediately upon login

### ISSUE THREAD

**Issue by searchingforpants** [astralapp/astral#309]
As of yesterday, every login attempt to [https://app.astralapp.com](https://app.astralapp.com) results in an immediate forced logoff. This is regardless of browser and after clearing cache.

With developer tools open I can see a GET to [https://app.astralapp.com/api/stars/github?](https://app.astralapp.com/api/stars/github?) returning a 500 error.

Portions of the API that don't seem to rely on Github (e.g. [https://app.astralapp.com/api/stars](https://app.astralapp.com/api/stars) return without issue.

As far as I can tell what I am experiencing is identical to a previously closed issue (#281) from September 2019. The solution appears to be clearing out the current auth token. Is this something a user can do on his/her own?

**Comment by syropian** [comment]
Hey, thanks for the report.

Normally you can clear your access token in the user settings modal by using the Revoke Access button but since you can't log in, I can manually clear it for you

**Comment by searchingforpants** [comment]
Thanks, I just tried logging in again and the behavior hasn't changed as far as I can tell.

**Comment by syropian** [comment]
Hm, that's odd. I'm still not seeing an access token on your account. I would try revoking access to Astral in your own GitHub settings, and then trying to re-log in to Astral.

**Comment by searchingforpants** [comment]
That did the trick! I'm able to log in without issue now.

Just for future reference, revoking and re-authorizing ("Settings" > "Applications" > "Authorized OAuth Apps") was one if the first things I tried before you cleared my token server-side, but on its own it was not enough.

**Comment by FunnyWolf** [comment]
> Hm, that's odd. I'm still not seeing an access token on your account. I would try revoking access to Astral in your own GitHub settings, and then trying to re-log in to Astral.

i have the same issue ,but i still can not login in after revoking and re-authorizing ("Settings" > "Applications" > "Authorized OAuth Apps")

**Comment by syropian** [comment]
@FunnyWolf Thanks, I'm actually running into the same thing on my own account as well! I'm still not sure what's going on, but I'll dig a little to try and find the root cause.

**Comment by syropian** [comment]
I just pushed a change that clears your access token if GitHub ever ends up returning a 401 — this should at least prevent the loop of trying to login and immediately getting kicked back out.
