### ISSUE TITLE
[Self Hosted Deploy] Cloudron.io App

### ISSUE THREAD

**Issue by tomershvueli** [astralapp/astral#336]
This isn't strictly an issue per se, and I'm happy to move this documentation somewhere else if it makes more sense, but I just wanted to inform the Astral App community that Astral has been packaged and deployed for [Cloudron](https://www.cloudron.io/index.html) (a self hosted platform with 1-click app installs, [obligatory referral link](https://cloudron.io/?refcode=3cdd3151023268c0)) on the [Cloudron App Store](https://www.cloudron.io/store/com.astralapp.cloudronapp.html). 

Thanks for all the great work that's been done on this app! Hopefully this will allow more people to take advantage of this application and keep their Github stars in check :)

**Comment by syropian** [comment]
Thanks @tomershvueli ! I'll get this added to the readme soon 👍🏻

**Comment by syropian** [comment]
Added! I'll probably refine the "Deploying" section at another date, but the link is there.
