### ISSUE TITLE
Hosted version throw 404 github page

### ISSUE THREAD

**Issue by kakawait** [astralapp/astral#364]
I've tried the free hosted version but after login to GitHub I'm redirected to https://github.com/login/oauth/authorize which is a 404 page

![Screenshot_20220101-195239.jpg](https://user-images.githubusercontent.com/275609/147857982-dc32a7b8-8933-431f-84f4-af9d0a79d6d5.jpg)

**Comment by syropian** [comment]
Hm that seems unusual. I just tried logging in and it worked fine, however it _could_ be an issue with account creation but I'm seeing lots of successful sign ups and no other reports of issues.

**Comment by kakawait** [comment]
I'll try on desktop. Maybe is due to my mobile setup which unusual (android + firefox mobile). I'll keep you in touch.

**Comment by kakawait** [comment]
I confirm on desktop (Linux + firefox) no issue... And now since my account is created on Astral side I've no more issue on my mobile device. 
I think can be close if I'm only people reporting that issue
