### ISSUE TITLE
Which environment vars are needed?

### ISSUE THREAD

**Issue by obvionaoe** [astralapp/astral#371]
So, I'm trying to create a Docker image using only php-fpm but I'm not sure what variables are needed for specific cases.

Could you add documentation regarding the environment variables and how they're loaded into the app?

Like for when you use SQLite is DB_PORT also needed?

Thanks

**Comment by syropian** [comment]
@obvionaoe Everything except `GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET`, and `GITHUB_CLIENT_CALLBACK_URL` are default Laravel env vars — fill them out if you need them, otherwise leave them blank. In your instance, you shouldn't need a port for SQLite so you can leave it blank

**Comment by obvionaoe** [comment]
Ok, thanks!
