### ISSUE TITLE
Highest Level Caching

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#40]
The current plan I have for step 1 of caching is to use a Middleware class to cache any get requests which return http status codes in the region of 200-300. 

The cache TTL will be configurable via .env, but probably set to around 1 hour or so.

Does anybody have any insight as to why this may not be a good idea? I can't see any bad idea.

Perhaps to begin with, it should not apply to the api routing group, and we can deal with that in a more specialised way, but caching general get requests is a good start.

**Comment by alexbowers** [comment]
Looking into how the app works, I have this backwards. Getting the /dashboard route would not work. 

I'll look into it more, but dont think magic caching is going to be a viable solution due to being SPA.

**Comment by syropian** [comment]
Hm, could we still not use the middleware in most of the api route group routes? `/dashboard` is a client-side route, but anything with `/api` is a server-side route.

**Comment by alexbowers** [comment]
Yeah, we can apply a middleware to the API route group.

**Comment by syropian** [comment]
There are a few special cases where we wouldn't want the middleware caching though. Namely, fetching the stars from GitHub, as I had to write a pretty custom solution for caching that data, due to the fact that the GitHub API paginates the response.
