### ISSUE TITLE
is this project still lively ?

### ISSUE THREAD

**Issue by xinity** [astralapp/astral#410]
last commit on master is 3 years old, i'm concerned :(

**Comment by syropian** [comment]
Hey @xinity - there's a couple discussion posts that touch on the future of this project. I realize the posts themselves are quite old, but they're technically still accurate. As of right now I don't have an official release date for the next version of Astral, but rest assured I won't let it die. My life just got really crazy post-pandemic and finding the time and energy to continue pushing through has been admittedly difficult. 

Posts:
- https://github.com/astralapp/astral/discussions/340
- https://github.com/astralapp/astral/discussions/393

**Comment by syropian** [comment]
> In the era when AI translation is popular, translation will be a very easy task. Have you considered supporting the in18 function?

i18n support probably won't ship with the `next` launch but I'll be looking to ship it shortly after.

**Comment by a67793581** [comment]
@syropian  I find tagging to be a very tedious task. I hope to add a new feature that utilizes AI to analyze repositories and set tags.

**Comment by alvarobyrne** [comment]
Above all, thank you very much for this wonderful project! I’m wondering if the image below is just a temporary issue or if it means that the project will no longer be available.

<img width="1687" alt="image" src="https://github.com/user-attachments/assets/51daecd0-db62-44cc-a538-44422d94a001">

Thank you for your attention and assistance.

Thanks in advance!

**Comment by syropian** [comment]
Hey @alvarobyrne , turns out the server Astral was on was so old it didn't even have the required package versions to regenerate the SSL cert correctly. I _just_ finished migrating the site to a new server so everything should be back up and running now (except for the marketing site, I'll get it back up later). Thanks for your patience!

**Comment by alvarobyrne** [comment]
> Hey @alvarobyrne , turns out the server Astral was on was so old it didn't even have the required package versions to regenerate the SSL cert correctly. I _just_ finished migrating the site to a new server so everything should be back up and running now (except for the marketing site, I'll get it back up later). Thanks for your patience!

Well done, thank you very much, congrats, kudos!
