### ISSUE TITLE
Hosted astralapp.com: `Invalid SSL certificate Error code 526`

### ISSUE THREAD

**Issue by evdcush** [astralapp/astral#415]
Hello and thank you for providing such a great resource!

I recently tried visiting the hosted https://astralapp.com, but got an "Invalid SSL certificate" error.

Is the hosted version no longer available?

**Comment by syropian** [comment]
Hey there,

Unfortunately my server was unable to properly re-issue its SSL cert and I'm away at my cottage with no computer until Monday 🤦‍♂️

I apologize for the inconvenience, I'll be sure to try and get it back up when I get home!

**Comment by evdcush** [comment]
Phew! I was worried!
Thank you so much!

**Comment by syropian** [comment]
Hi! Just letting you know the site should be back up now.

**Comment by evdcush** [comment]
Thank you! 

I'm no longer experiencing the `526` cert error, but now I'm getting a timeout error `522` 😅 

But I trust it will be up soon!

**Comment by syropian** [comment]
@evdcush Seems to be working fine for me — you may need to clear your browser cache or something?

**Comment by syropian** [comment]
@evdcush Also, make sure you're visiting the app url, not the marketing site, which is still down. https://app.astralapp.com

**Comment by evdcush** [comment]
> @evdcush Also, make sure you're visiting the app url, not the marketing site, which is still down. https://app.astralapp.com

Ah this was the problem! I had confused the two, and was trying to access https://astralapp.com.
The app works! 🎉

Thanks @syropian! :godmode:
