### ISSUE TITLE
TLS Certificate on astralapp.com broken

### ISSUE THREAD

**Issue by Maddosaurus** [astralapp/astral#416]
Hey there! 
Looks like https://astralapp.com/ is currently broken as cloudflare is rather unhappy about the certificate.
Any chances of getting the hosted version up and running again?
I really enjoyed using and demoing it on a whim :heart:

**Comment by syropian** [comment]
Duplicate of #415

**Comment by syropian** [comment]
Should be back up Monday evening or Tuesday morning EST time! Sorry for the inconvenience

**Comment by syropian** [comment]
Hello! The site is now back up, thanks for your patience!

**Comment by Maddosaurus** [comment]
@syropian Are you sure about that? astralapp.com now runs into Cloudflares' 522 :hourglass:

**Comment by syropian** [comment]
The app lives at https://app.astralapp.com and should work fine.

**Comment by Maddosaurus** [comment]
Ah yes, thank you very much!
