### ISSUE TITLE
Setup Improvements

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#42]
Setting up and installing locally has proven to be not completely straightforward. I think the base page should return the steps based on what you have left to do.

We'll see what steps are needed, but I think we can improve it quite a lot.

Errors encountered along the way:

- [ ] No .env file (.env.example) - Generic 'Something went wrong' page. (not sure a solution to this is possible?)
- [ ] No key generated - Cipher error (Run: php artisan key:generate)
- [ ] No github client ID set (should not show button until the ID's are present)

**Comment by syropian** [comment]
Hm, you may be under the impression that Astral is meant to be self-installed, but its a hosted app (http://app.astralapp.com).

**Comment by alexbowers** [comment]
Ah okay. There is still the possibility of people installing it themselves (being OS and all). Installation should be made as easy as possible - Though, i guess since it isn't a priority, its a low level task.

**Comment by syropian** [comment]
Yeah, self-installation isn't really a priority at this point. Lots of other stuff to tackle!
