### ISSUE TITLE
Issue errors in a better way

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#43]
If something goes wrong with authentication currently, it is not clear. A generic exception message is thrown, and not much can be seen from there. `InvalidStateException in AbstractProvider.php line 191`

**Comment by alexbowers** [comment]
this again, was a local issue (due to not having correct config - Not an issue in RL, but perhaps nicer messaging can be dealt with).

Low priority.

**Comment by syropian** [comment]
Yeah, pretty much all the routes/controller actions need better error handling in general. That'll hopefully be part of if their refactoring
