### ISSUE TITLE
SPA url changes

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#44]
Since this appears (at first glance) to be a Single Page Application, currently there are different page states (such as whether we are on the 'All Stars' page or 'Untagged Stars' etc, but refreshing the page loses the current state.

Using some form of URL changing would help significantly with this.

Angular can do this, I imagine Vue can too (since i believe vue is being used?)

**Comment by syropian** [comment]
This sort of happens, when you click a tag the url gets updated. I have not gotten to writing the untagged state yet though. It's pretty trivial to update the url though.
