### ISSUE TITLE
[Security] Do not broadcast X-Powered-By

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#45]
For security reasons, broadcasting X-Powered-By is not really a good idea.

**Comment by syropian** [comment]
What's currently broadcasting it?

**Comment by alexbowers** [comment]
Ajax calls have it in the Response Headers.

By the look of it, its Apache

![image](https://cloud.githubusercontent.com/assets/842974/15456553/b9e96dbc-206b-11e6-90aa-96e23cc6e8d1.png)

**Comment by alexbowers** [comment]
@syropian This needs revisiting I think.

**Comment by syropian** [comment]
Fixed by adding `proxy_hide_header X-Powered-By;` in the nginx confs.

**Comment by alexbowers** [comment]
Great thanks.

**Comment by alexbowers** [comment]
We were planning a while ago of going to PHP 7, is that complete yet, or still in progress?

**Comment by syropian** [comment]
@alexbowers It's currently running on a PHP 7 server.

**Comment by alexbowers** [comment]
Great. I might do some refactors to php 7 at some point.

**Comment by syropian** [comment]
That would be awesome 👍
