### ISSUE TITLE
Rewrite the API server in golang

### ISSUE THREAD

**Issue by lucmichalski** [astralapp/astral#58]
HI guys,

Hope u are doing well !

I was wondering if it would not be better to rewrite the API server with some in golang; it would lighter and faster.

Easy one based on SQLITE3, can be extended to MySQL with GORM, u can check this example:
https://github.com/null-none/qor-init

Cheers,
Luc Michalski

**Comment by alexbowers** [comment]
Personally I have no experience with GoLang, and it is probably the same situation with the other members.

As for possibly doing it in golang, whilst it may be faster and lighter, it doesn't help much if we can't understand the Pull Request / code. 

@syropian Would this be accepted? I have been meaning to learn golang, but I wouldn't be able to verify a PR properly.

**Comment by joshhornby** [comment]
I don't see any benefit in moving to Go, PHP 7 brings speed improvements and once the code refactor is complete I am sure we will see many benefits, one of which will be increased performance .

**Comment by alexbowers** [comment]
I agree, since the next version will be PHP 7 based.

**Comment by syropian** [comment]
Yeah, at the moment I have no desire to rewrite the whole server in Go, as none of us have any real experience with it. I've been very impressed with PHP7's performance, and I think for now that'll be fine.
