### ISSUE TITLE
Dockerfile - Docker-Compose

### ISSUE THREAD

**Issue by lucmichalski** [astralapp/astral#59]
Re,

Was wondering if providing a launch script with some containers, would make easier the local tests of Astral. (eg. https://github.com/dydx/alpine-nginx-php-mariadb)

What is the license for Astral if u want to contribute ?

Cheers,
Luc

**Comment by alexbowers** [comment]
The licence is listed here: https://github.com/astralapp/astral/blob/master/LICENSE

**Comment by syropian** [comment]
I don't have much (read any) experience with Docker. Are you having trouble getting Homestead up and running?
