### ISSUE TITLE
Compiling astral

### ISSUE THREAD

**Issue by bigdoods** [astralapp/astral#61]
Hello,

I am trying to build the local version as described in your readme and I am a bit lost as that I have no experience with laravel and php.

I am at the Compile step in your instructions. Could you make it clear what that means for me please?

I have tried running `compose composer.json` and I receive the following error: 
Error: no "compose" mailcap rules found for type "application/json"

Thanks in advance!

John

**Comment by syropian** [comment]
Hi! First of all you'll need to globally install [Composer](https://getcomposer.org/). After that just cd into the project and run `composer install`.

**Comment by bigdoods** [comment]
Thank you!
