### ISSUE TITLE
Unable to rename a tag

### ISSUE THREAD

**Issue by nogorilla** [astralapp/astral#79]
When attempting to rename a tag, after clicking "Save" the error appears "The name field is required" despite having an entry in the tag's name field

![screenshot](https://cloud.githubusercontent.com/assets/1786677/18214614/d98ad420-711b-11e6-9077-c675f0da9835.png)

**Comment by syropian** [comment]
Whoops, you're right! I'll look into pushing a fix for this later today when I get off work.

**Comment by w00p** [comment]
Any update on this?

**Comment by syropian** [comment]
@w00p Haven't had time to fix this, I can try and get to it this weekend.

**Comment by syropian** [comment]
Will be pushing and deploying a fix for this in a couple hours.

**Comment by syropian** [comment]
Fixed in #87
