### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#8]
_From @irace on November 25, 2014 20:17_

It'd be great to be able to navigate the Astral UI and apply tags using keyboard shortcuts. One low-hanging fruit shortcut would be tapping enter to save and dismiss the tag popover.

_Copied from original issue: syropian/astral-issues#17_

**Comment by syropian** [comment]
@irace Hitting enter now saves the tags and dismisses the popover :+1:

**Comment by muescha** [comment]
@syropian no it don't have this behavoir not anymore :(
see #118
