### ISSUE TITLE
Unable to display a repo if no readme is present

### ISSUE THREAD

**Issue by nogorilla** [astralapp/astral#80]
If a repo does not have a readme file, the repo cannot be displayed. This prevents editing of tags and notes for the repo

**Comment by syropian** [comment]
@nogorilla Could you include a link of an example repo that has no readme? Thanks!

**Comment by nogorilla** [comment]
https://github.com/BrewPi/brewpi-www

**Comment by gagomes** [comment]
I'm seeing the same at astralapp.com

**Comment by alexbowers** [comment]
I'll get around to fixing this tomorrow probably. In the meantime, feel free to submit a PR if you want to fix it.

**Comment by alexbowers** [comment]
Or do you have WIP @syropian ?

**Comment by syropian** [comment]
@alexbowers You can tackle this if you'd like. I'm going to try fix tag renaming tonight.

**Comment by alexbowers** [comment]
Ok cool.

**Comment by alexbowers** [comment]
Work in progress made here: https://github.com/astralapp/astral/pull/99

**Comment by syropian** [comment]
Fixed in #99
