### ISSUE TITLE
Changes to vue components

### ISSUE THREAD

**Issue by w00p** [astralapp/astral#83]
Hi,

After doing some changes to vue files, how to get the changes to work?

**Comment by alexbowers** [comment]
You will need to make sure you run `gulp` in the command line to compile the assets down.

**Comment by w00p** [comment]
Yeah, but i get the following error when running gulp:

`/home/user/domains/domain/public_html/node_modules/laravel-elixir-vueify/index.js:3
Elixir.config.js.browserify.transformers.push({
TypeError: Cannot read property 'transformers' of undefined
    at Object.<anonymous> (/home/user/domains/domain/public_html/node_modules/laravel-elixir-vueify/index.js:3:28)`

**Comment by alexbowers** [comment]
Are you definitely up to date `npm install`

**Comment by syropian** [comment]
Possibly a breaking change in Elixir. I'll look into this soon.

**Comment by syropian** [comment]
@w00p Can you please try pulling on master, (and if you have a feature branch, merge master into it) and try running Gulp again?

**Comment by w00p** [comment]
Thank you @syropian :) Did a git pull and npm install. Now gulp works perfect!

**Comment by syropian** [comment]
Great, thanks!
