### ISSUE TITLE
Usability issues and suggestions

### ISSUE THREAD

**Issue by gagomes** [astralapp/astral#84]
1. When adding tags to a star in firefox (Linux) the input box does not get cursor focus unless clicked. I believe this works fine in OSX.
2. Provide a feature to tell astral to flush the cache away and refresh it, so that if we unstar stars, these are evicted away.
3. Please add a feature to select multiple repos and apply tag(s) to all selected.

**Comment by alexbowers** [comment]
Thanks for the feedback.

2. Is being tracked on a separate issue. https://github.com/astralapp/astral/issues/88

**Comment by syropian** [comment]
Note 2 was added in #111

**Comment by AntoineTurmel** [comment]
+1 for multiselect 👍

**Comment by syropian** [comment]
@AntoineTurmel Multi-select has been added in the `v3` branch. Thanks for reminding me to tag this issue correctly 😅

**Comment by AntoineTurmel** [comment]
@syropian oh nevermind, but is it deployed at https://astralapp.com yet ?

**Comment by syropian** [comment]
@AntoineTurmel Not yet, the `v3` branch is a complete rewrite and redesign of the entire app, and will be likely launching early August.

**Comment by AntoineTurmel** [comment]
@syropian ok nice !
