### ISSUE TITLE
Relative URLs not working

### ISSUE THREAD

**Issue by revolter** [astralapp/astral#85]
If a repository has an image with relative URL, Astral tries to load if from the `astralapp.com` domain.

This is one repository that causes problems: https://github.com/cruffenach/CRToast . You can see that in Astral, the screenshots are not showing up.

I am willing to try to open a PR for this if pointed to the right file, as I don't know the project structure, nor Angular or Vue.

**Comment by syropian** [comment]
I'm going to look into this a little further, but I think this is an issue with repos that use images _from the repo itself_ inside the readme. Github can show it fine as it's hosting the content, but as we are not there isn't a way to show those images. There's possibly some regex foo to transform the markdown on fetch but that may get messy.

**Comment by alexbowers** [comment]
I'm happy to fix this @syropian if @revolter isn't able to

**Comment by revolter** [comment]
> but I think this is an issue with repos that use images from the repo itself inside the readme. Github can show it fine as it's hosting the content

This is what I wanted to say. Well, I currently don't see another way than changing the markdown before printing it.

**Comment by revolter** [comment]
@alexbowers, That would be great! What idea do you have in mind?

**Comment by alexbowers** [comment]
A simple regex replace on the readme for `src, href` etc -> `src="/"` where `/` is not a `//` (to check for relative).

From there, generate a `raw.github` url for the path to the image, and use that in the src.

**Comment by alexbowers** [comment]
Eg, for one of the screenshots in the provided file, it is this path: https://raw.githubusercontent.com/cruffenach/CRToast/master/screenshots/demo.gif

Which is obtainable by appending `?raw=true` to the URL already being used.

**Comment by revolter** [comment]
That was my thought too, but I didn't work with JS in a couple of years, so if you can do it, I would be grateful.

**Comment by alexbowers** [comment]
Yeah i'll try to get the chance this evening to give it a go.

**Comment by revolter** [comment]
> Which is obtainable by appending ?raw=true to the URL already being used.

Wait, the URL in the README is `screenshots/demo.gif`, so it needs the first part of the URL too.

**Comment by alexbowers** [comment]
Yeah, the regex will be able to replace the relative URL with the URL of their repository, which I believe we already have [here](https://github.com/astralapp/astral/blob/master/resources/assets/js/store/actions.js#L90).

That will allow me to generate a `//github.com/${name}/${path}?raw=true`.

A bit more work than that is required, incase the URL already has query parameters etc, but thats the general idea

**Comment by syropian** [comment]
@alexbowers Thanks! Would be very grateful if you took a stab at it :)

**Comment by alexbowers** [comment]
@syropian Can you take a look at #86?

**Comment by alexbowers** [comment]
@revolter If you want to look over the implementation too. If approved, it should go live sometime soon.

**Comment by syropian** [comment]
@alexbowers I'll give it a look right now!
