### ISSUE TITLE
Add a button that forces a refresh of stars

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#88]
This should bust the stars cache, and re-fetch all stars from Github. It should have a throttle of one refresh every 5 minutes on a per user basis.

**Comment by alexbowers** [comment]
This is something I would have found useful.

Then I realised for dev mode, just `php artisan cache:clear` does it.

**Comment by syropian** [comment]
@alexbowers Yeah, easy to do in dev mode, but this is for users who want to immediately organize something they just starred. Cache is currently set to 2 hours, which is probably a little long for some people :)

**Comment by alexbowers** [comment]
Feeding on from #109, perhaps having a `last updated X` message showing when cache is from would be useful?

**Comment by syropian** [comment]
Added in #111
