### ISSUE TITLE
Upgrade to Laravel 5.3

### ISSUE THREAD

**Issue by alexbowers** [astralapp/astral#90]
We can use Laravel Shift for this, its $9 but does the work for us.

**Comment by syropian** [comment]
That's pretty sweet, I'll get this going after work tonight.

**Comment by alexbowers** [comment]
I didn't get around to this today, will hopefully in the next few days.

**Comment by alexbowers** [comment]
Delay was a little longer than expected, can you review the PR @syropian ?

**Comment by syropian** [comment]
Yup! I'll get to this tomorrow, thanks!
