### ISSUE TITLE
App is slow when user have abobe 1000 stars

### ISSUE THREAD

**Issue by pantchox** [astralapp/astral#91]
the 'Loading stars' take too long.

Maybe the way the data is being loaded and rendered is not optimal.

**Comment by syropian** [comment]
Github paginates its API, so there's no way to fetch 1000+ stars right away. It has to be done recursively to make perceived load time decent. Right now the Github API client I'm using is pulling 30 stars per page, but they recently merged a PR I wrote that kets you specify how many stars per page you want. GitHub still limits this though, and I don't think you can pull more than 50 per page.

Furthermore, this initial load only happens once every 2 hours, as data is cached when all stars have loaded, making subsequent fetches much faster.
