### ISSUE TITLE
Certain tag names convert to broken urls

### ISSUE THREAD

**Issue by syropian** [astralapp/astral#93]

**Comment by syropian** [comment]
Tags such as "C#" aren't url safe and become unclickable. This seems to be the case with tags using alternate languages such as Chinese.

**Comment by alexbowers** [comment]
URL Encoding and Decoding may be the way to go on this:

https://3v4l.org/PqSXO

It may not be the prettiest URLs, but it'd get the job done.

**Comment by syropian** [comment]
url encoding is fine with me. 👍

**Comment by zhaohuiyingxue** [comment]
you can add chinese tag,but can not view list with this tag. 
eg. add tag with name “中文” or “C#”,the json in response (https://app.astralapp.com/api/tags) like this:
{"id":105918,"name":"C#","description":null,"sort_order":0,"created_at":"2016-10-12 06:29:11","updated_at":"2016-10-12 06:54:23","slug":"c","color":null,"stars_count":36},{"id":106141,"name":"\u4e2d\u6587","description":"","sort_order":13,"created_at":"2016-10-13 03:05:37","updated_at":"2016-10-13 03:05:37","slug":"","color":null,"stars_count":0}

because the slug is empty string ,so if you click the tag name in left list in page ,the url goto "https://app.astralapp.com/dashboard/tag/" 

sorry , my english is very poor.....haha

**Comment by alexbowers** [comment]
Just edited your command to add some formatting to json.

**Comment by syropian** [comment]
@alexbowers Since some tags like `C#` get the slug of `c` (which is still valid but incorrect) we'll probably need to write an artisan command to re-slug all tags. There's already one to populate tags that don't have a slug (see https://github.com/astralapp/astral/blob/master/app/Console/Commands/AddTagSlugs.php), but we'll need a modified one to fix other slugs. 

Not sure if there's a way to filter only tags that might be broken but that would speed things up. Otherwise we just have to apply it across all tags.

**Comment by alexbowers** [comment]
What we could do is fetch all tags, apply the change in php, and if the value is different run the update query. This would speed it up somewhat.

**Comment by syropian** [comment]
@alexbowers Would you be able to tackle this? I would say it's pretty high priority over other tasks atm.

**Comment by alexbowers** [comment]
Sure can you send me a database so I can test the migration ?

**Comment by syropian** [comment]
@alexbowers Just emailed you a DB dump

**Comment by alexbowers** [comment]
Fixed in #105. Thoughts?

**Comment by syropian** [comment]
@alexbowers Awesome stuff! I applied the fixes on the production server. Thanks!

**Comment by zhaohuiyingxue** [comment]
now some tags like "中文"  which is valid but incorrect,the json like this:
```json
{
    "id": 106259,
    "name": "\u5de5\u5177",
    "description": "",
    "sort_order": 14,
    "created_at": "2016-10-14 02:02:07",
    "updated_at": "2016-10-14 02:02:07",
    "slug": "e4b8ade69687",
    "color": null,
    "stars_count": 0
}
```
but I think the json for results should be that way:
```json
{
    ...
    "name": "\u5de5\u5177",
    "slug": "%E4%B8%AD%E6%96%87"
}
```
it's means you can only use function with urlencode（with utf-8）。
eg. 
C++ --> C%2B%2B
C# --> C%23
中文 ~`!@#$%^&*()_+-={}[]|\:;\"'<>?,./  --> %E4%B8%AD%E6%96%87+%7E%60%21%40%23%24%25%5E%26%2A%28%29_%2B-%3D%7B%7D%5B%5D%7C%5C%3A%3B%22%27%3C%3E%3F%2C.%2F
.net --> .net（nochanges ,url can understand）

you can click links:
https://github.com/search?l=php&q=%E4%B8%AD%E6%96%87
https://github.com/search?l=php&q=%E4%B8%AD%E6%96%87+%7E%60%21%40%23%24%25%5E%26%2A%28%29_%2B-%3D%7B%7D%5B%5D%7C%5C%3A%3B%22%27%3C%3E%3F%2C.%2F

**Comment by zhaohuiyingxue** [comment]
You can remove replace_encoded_space, replace_plus,str_slug these functions(in line 32\33\35 of file 'TagSlugger.php') eg. use urlencode to translation ‘中文’ to '%E4%B8%AD%E6%96%87', and use replace_encoded_space, replace_plus,str_slug to 'e4b8ade69687'  is meaningless
p.s. #77 is fixed now with this commit;
