### ISSUE TITLE
Memory Consumption too high

### ISSUE THREAD

**Issue by Ibrahim-Islam** [astralapp/astral#94]
After a while using AstralApp, this is what the memory consumption looks like:

![astral_mem](https://cloud.githubusercontent.com/assets/6401874/19233622/6f43443e-8f08-11e6-8dce-bce238e194ce.png)

**Comment by alexbowers** [comment]
More info:

@Ibrahim-Islam has approximately 570 stars.

Any more information from you @Ibrahim-Islam Would be useful. 

Ie. how many tags do you have?

**Comment by Ibrahim-Islam** [comment]
@alexbowers  I have 8 tags.

**Comment by alexbowers** [comment]
Thanks, please can you provide:

- OS Version
- Browser Version

**Comment by Ibrahim-Islam** [comment]
@alexbowers OS: Window 8.1, Browser: Chrome Version 53.0.2785.143 m

**Comment by alexbowers** [comment]
Thanks, we'll look into it soon.
